config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :equipment_groups, only: [:new, :index, :create, :update, :destroy]
  get 'equipment_groups/:id/table' => 'equipment_groups#table', as: :equipment_group_table
  get 'equipment_groups/:id/just_the_table' => 'equipment_groups#just_the_table', as: :just_the_table
  get 'equipment_groups/:id/tv_mode' => 'equipment_groups#tv_mode', as: :tv_mode
  get 'equipment_groups/:id/settings' => 'equipment_groups#settings', as: :equipment_group_settings
  resources :equipment, only: [:edit, :update]
  resources :log_entries, only: [:create]
  get 'log_entries/new_row/:id' => 'log_entries#new_row', as: :new_row
  get 'log_entries/new_row_simple/:id' => 'log_entries#new_row_simple', as: :new_row_simple

end

app/models/equipment.rb
# Internal: A piece of Equipment is an object you want to track various
# Measurement against. Equipment belong to an EquipmentGroup. Equipment have
# many Measurement.
class Equipment < ActiveRecord::Base
  has_paper_trail
  belongs_to :equipment_group
  has_many :measurements, dependent: :destroy

  validates :name, presence: true, length: { maximum: 40 }
  validates :name_position, presence: true

  accepts_nested_attributes_for :measurements, :allow_destroy => true
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate

  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
  end

  # GET /equipment/new
  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.name_position = Time.now.to_i

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to equipment_group_table_path(@equipment.equipment_group), notice: 'Equipment was successfully created.' }
        format.json { render :show, status: :created, location: @equipment }
      else
        format.html { render :new }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    respond_to do |format|
      if @equipment.update(equipment_params)
        format.html { redirect_to equipment_group_table_path(@equipment.equipment_group), notice: 'Equipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment }
      else
        format.html { render :edit }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    respond_to do |format|
      format.html { redirect_to equipment_index_url, notice: 'Equipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment
      @equipment = Equipment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_params
      params.require(:equipment).permit(:name, :name_position, :equipment_group_id, measurements_attributes: [:id, :name, :unit, :is_bool, :name_position, :equipment_id, :_destroy])
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_form.html.haml
.row
  .col-md-12
    %h1
      %strong
        = @equipment.name
.row
  .col-md-12
    = nested_form_for @equipment do |f|
      - if @equipment.errors.any?
        #error_explanation
          %h2= "#{pluralize(@equipment.errors.count, "error")} prohibited this equipment from being saved:"
          %ul
            - @equipment.errors.full_messages.each do |msg|
              %li= msg
      .panel.panel-primary
        .panel-heading
          %h3.panel-title.text-center
            %strong Measurements
        .panel-body
          = f.fields_for :measurements do |m|
            .row
              .col-md-3
                .form-group
                  %label Name
                  = m.text_field :name, :class => 'form-control'
              .col-md-2
                .form-group
                  %label Unit
                  = m.text_field :unit, :class => 'form-control'
              .col-md-2
                .form-group
                  %label Position
                  = m.number_field :name_position, :class => 'form-control'
              .col-md-3
                .form-group
                  %label True/False Measurement?
                  = m.check_box :is_bool, :class => 'form-control'
              .col-md-2
                .form-group
                  = m.link_to_remove "<div class='btn btn-md btn-danger' style='margin-top: 25px;'><span class='glyphicon glyphicon-minus' style='color: white;'></span></div>".html_safe
          .row
            .col-md-12
              = f.link_to_add "<div class='btn btn-md btn-success'><span class='glyphicon glyphicon-plus' style='color: white;'></span></div>".html_safe, :measurements
        .panel-footer
          .row
            .col-md-12
              %button.pull-right.btn.btn-primary.form-control{:type => :submit, :name => "commit"}
                %span.glyphicon.glyphicon-check
                Save

app/views/equipment/edit.html.haml
.container
  = render 'form'

app/views/equipment/index.html.haml
%h1 Listing equipment

%table
  %tr
    %th Name
    %th Name position
    %th Equipment group
    %th
    %th
    %th

  - @equipment.each do |equipment|
    %tr
      %td= equipment.name
      %td= equipment.name_position
      %td= equipment.equipment_group_id
      %td= link_to 'Show', equipment
      %td= link_to 'Edit', edit_equipment_path(equipment)
      %td= link_to 'Destroy', equipment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Equipment', new_equipment_path

app/views/equipment/new.html.haml
%h1 New equipment

= render 'form'

= link_to 'Back', equipment_index_path

app/views/equipment/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @equipment.name
%p
  %b Name position:
  = @equipment.name_position
%p
  %b Equipment group:
  = @equipment.equipment_group_id

= link_to 'Edit', edit_equipment_path(@equipment)
\|
= link_to 'Back', equipment_index_path