config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :equipment_groups, only: [:new, :index, :create, :update, :destroy]
  get 'equipment_groups/:id/table' => 'equipment_groups#table', as: :equipment_group_table
  get 'equipment_groups/:id/just_the_table' => 'equipment_groups#just_the_table', as: :just_the_table
  get 'equipment_groups/:id/tv_mode' => 'equipment_groups#tv_mode', as: :tv_mode
  get 'equipment_groups/:id/settings' => 'equipment_groups#settings', as: :equipment_group_settings
  resources :equipment, only: [:edit, :update]
  resources :log_entries, only: [:create]
  get 'log_entries/new_row/:id' => 'log_entries#new_row', as: :new_row
  get 'log_entries/new_row_simple/:id' => 'log_entries#new_row_simple', as: :new_row_simple

end

app/models/equipment_group.rb
# Internal: A group of related equipment (Paint Line, Brewery Tanks, Chrome
# Platers, etc...). An EquipmentGroup equates to one table. EquipmentGroup
# belongs to a User. EquipmentGroup have many pieces of Equipment.
class EquipmentGroup < ActiveRecord::Base
  has_paper_trail
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :equipment, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :authorized_users, through: :authorizations, :source => :user
  has_many :measurements, through: :equipment

  validates :name, presence: true, length: { maximum: 40 }

  accepts_nested_attributes_for :equipment, :allow_destroy => true
  accepts_nested_attributes_for :measurements, :allow_destroy => true
  accepts_nested_attributes_for :authorizations, :allow_destroy => true

end

app/controllers/equipment_groups_controller.rb
class EquipmentGroupsController < ApplicationController
  before_action :set_equipment_group, only: [:show, :edit, :update, :destroy, :table, :just_the_table, :tv_mode, :new_row, :settings]
  before_filter :check_read_permission, except: [:new, :create, :index]
  before_filter :authenticate, except: [:table, :just_the_table, :tv_mode]

  # GET /equipment_groups
  # GET /equipment_groups.json
  def index
  end

  # GET /equipment_groups/1
  # GET /equipment_groups/1.json
  def show
  end

  # GET /equipment_groups/new
  def new
    @equipment_group = EquipmentGroup.new
    @equipment_group.public_access = false
  end

  # GET /equipment_groups/1/edit
  def edit
  end

  # POST /equipment_groups
  # POST /equipment_groups.json
  def create
    @equipment_group = EquipmentGroup.new(equipment_group_params)
    @equipment_group.owner = current_user
    @equipment_group.name_position = Time.now.to_i
    @equipment_group.public_access = false

    respond_to do |format|
      if @equipment_group.save
        format.html { redirect_to equipment_group_table_path(@equipment_group), notice: 'Equipment group was successfully created.' }
        format.json { render :show, status: :created, location: @equipment_group }
      else
        format.html { render :new }
        format.json { render json: @equipment_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipment_groups/1
  # PATCH/PUT /equipment_groups/1.json
  def update
    respond_to do |format|
      if @equipment_group.update(equipment_group_params)
        format.html { redirect_to equipment_group_table_path(@equipment_group), notice: 'Equipment group was successfully updated.' }
        format.json { render :show, status: :ok, location: @equipment_group }
      else
        format.html { render :edit }
        format.json { render json: @equipment_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment_groups/1
  # DELETE /equipment_groups/1.json
  def destroy
    @equipment_group.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Equipment group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def table
    authenticate unless @equipment_group.public_access
    @equipment = @equipment_group.equipment
  end

  def just_the_table
    authenticate unless @equipment_group.public_access
    @equipment = @equipment_group.equipment
    render :layout => "blank"
  end

  def tv_mode
    authenticate unless @equipment_group.public_access
    @equipment = @equipment_group.equipment
    render :layout => "blank"
  end

  def settings
    if current_user.is_owner(@equipment_group)
    else
      redirect_to root_url, :alert => "You don't have access to this area."
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipment_group
      @equipment_group = EquipmentGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def equipment_group_params
      params.require(:equipment_group).permit(:name, :name_position, :public_access, :user_id, equipment_attributes: [:id, :name, :name_position, :equipment_group_id, :_destroy], authorizations_attributes: [:id, :user_id, :equipment_group_id, :read_permission, :write_permission, :_destroy, :username])
    end

    def check_read_permission
      if @equipment_group.public_access
      else
        if user_signed_in?
          if current_user.is_owner(@equipment_group) or current_user.can_read(@equipment_group)
          else
            redirect_to root_url, :alert => "You don't have permission to see this."
          end
        else
          redirect_to root_url, :alert => "You don't have permission to see this."
        end
      end
    end
end

app/helpers/equipment_groups_helper.rb
module EquipmentGroupsHelper
end

app/views/equipment_groups/_form.html.haml
= form_for @equipment_group do |f|
  - if @equipment_group.errors.any?
    .row
      .col-md-12
        #error_explanation
          %h2= "#{pluralize(@equipment_group.errors.count, "error")} prohibited this equipment_group from being saved:"
          %ul
            - @equipment_group.errors.full_messages.each do |msg|
              %li= msg
  .row
    .col-md-10
      .form-group
        = f.text_field :name, :class => 'form-control', :placeholder => 'Table Name'
    .col-md-2
      .actions
        = f.submit 'Save', :class => 'btn btn-success'

app/views/equipment_groups/_just_the_table.html.haml
%table.table.table-condensed.table-striped{data: {url: equipment_group_table_path(@equipment_group) } }
  %tr
    %th.tv_heading.h4 Equipment
    %th.tv_heading.h4 Measurement
    %th.tv_heading.h4 Unit
    %th.tv_heading.h4 Lower Bound
    %th.tv_heading.h4 Upper Bound
    - if @equipment_group.measurements.empty?
      %th.tv_heading.h4 Infinity
      %tr
        %td{:colspan => 6}
          %h1.text-center
            %strong
              Why don't you add some Equipment and Measurements in the section below?
    - else
      - @equipment_group.measurements.first.values.last(5).reverse!.each do |v|
        %th.tv_heading.h4
          = v.log_entry.capture_date.strftime("%b %-d")
          %br
          = v.log_entry.capture_date.strftime("%k:%M")
  - @equipment.order(:name_position).each do |e|
    - e.measurements.order(:name_position).each do |m|
      %tr
      - if m === e.measurements.order(:name_position).first
        %td= e.name
      - else
        %td
      - if m.values.empty?
        %td= m.name
        %td= m.unit
        %td ?
        %td ?
        %td{ :rel => "tooltip", :class => "blue", :title => "N/A", :data => { :toggle => "tooltip", :placement => "top", :container => "body" } } N/A
      - else
        %td= m.name
        %td= m.unit
        %td= m.values.last.lower_bound_display
        %td= m.values.last.upper_bound_display
        - m.values.last(5).reverse!.each do |v|
          %td{ :rel => "tooltip", :class => "#{validation_color(v)}", :title => v.metadata, :data => { :toggle => "tooltip", :placement => "top", :container => "body" } }= v.value_display

app/views/equipment_groups/edit.html.haml
%h1 Editing equipment_group

= render 'form'

= link_to 'Show', @equipment_group
\|
= link_to 'Back', equipment_groups_path

app/views/equipment_groups/index.html.haml
%h1 Listing equipment_groups

%table
  %tr
    %th Name
    %th Name position
    %th
    %th
    %th

  - @equipment_groups.each do |equipment_group|
    %tr
      %td= equipment_group.name
      %td= equipment_group.name_position
      %td= link_to 'Show', equipment_group
      %td= link_to 'Edit', edit_equipment_group_path(equipment_group)
      %td= link_to 'Destroy', equipment_group, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Equipment group', new_equipment_group_path

app/views/equipment_groups/just_the_table.html.haml
%table.table.table-condensed.table-striped{data: {url: equipment_group_table_path(@equipment_group) } }
  %tr
    %th.tv_heading.h4 Equipment
    %th.tv_heading.h4 Measurement
    %th.tv_heading.h4 Unit
    %th.tv_heading.h4 Lower Bound
    %th.tv_heading.h4 Upper Bound
    - if @equipment_group.measurements.empty?
      %th.tv_heading.h4 Infinity
      %tr
        %td{:colspan => 6}
          %h1.text-center
            %strong
              Why don't you add some Equipment and Measurements in the section below?
    - else
      - @equipment_group.measurements.first.values.last(5).reverse!.each do |v|
        %th.tv_heading.h4
          = v.log_entry.capture_date.strftime("%b %-d")
          %br
          = v.log_entry.capture_date.strftime("%k:%M")
  - @equipment.order(:name_position).each do |e|
    - e.measurements.order(:name_position).each do |m|
      %tr
      - if m === e.measurements.order(:name_position).first
        %td= e.name
      - else
        %td
      - if m.values.empty?
        %td= m.name
        %td= m.unit
        %td ?
        %td ?
        %td{ :rel => "tooltip", :class => "blue", :title => "N/A", :data => { :toggle => "tooltip", :placement => "top", :container => "body" } } N/A
      - else
        %td= m.name
        %td= m.unit
        %td= m.values.last.lower_bound_display
        %td= m.values.last.upper_bound_display
        - m.values.last(5).reverse!.each do |v|
          %td{ :rel => "tooltip", :class => "#{validation_color(v)}", :title => v.metadata, :data => { :toggle => "tooltip", :placement => "top", :container => "body" } }= v.value_display

app/views/equipment_groups/new.html.haml
.container
  .row
    .col-md-12
      %h1 New Table
  = render 'form'

app/views/equipment_groups/settings.haml
.container
  .row
    .col-md-12
      %h1
        %strong
          %span.glyphicon.glyphicon-pencil{ :style => "color: red;", :rel => "tooltip", :title => "Click to edit", :data => { :toggle => "tooltip", :placement => "top", :container => "body" } }
          %span#TableName.rest-in-place{ :data => { :url => equipment_group_path(@equipment_group), :object => 'equipment_group', :attribute => 'name', :placeholder => 'Click to Edit' } }
            = @equipment_group.name
  .row
    .col-md-12
      .panel.panel-warning
        .panel-heading.text-center
          %strong
            %span.glyphicon.glyphicon-eye-open
            Permissions
            %span.glyphicon.glyphicon-pencil
        .panel-body
          = nested_form_for @equipment_group do |f|
            = f.fields_for :authorizations do |af|
              .row.push-bottom
                .col-md-4
                  = af.label :user_id, "Username"
                  = af.collection_select :user_id, User.order('username ASC').all, :id, :username, {}, :class => 'form-control'
                .col-md-3
                  = af.label :read_permission
                  = af.select :read_permission, options_for_select({ "True" => true, "False" => false }, af.object.read_permission), {}, { :class => 'form-control' }
                .col-md-3
                  = af.label :write_permission
                  = af.select :write_permission, options_for_select({ "True" => true, "False" => false }, af.object.write_permission), {}, { :class => 'form-control' }
                  = af.hidden_field :equipment_group_id, :class => 'form-control', :value => @equipment_group.id
                .col-md-2
                  = af.link_to_remove "<div class='btn btn-md btn-danger' style='margin-top: 25px;'><span class='glyphicon glyphicon-minus' style='color: white;'></span></div>".html_safe
            .row.push-bottom
              .col-md-12
                = f.link_to_add "<div class='btn btn-md btn-success'><span class='glyphicon glyphicon-plus' style='color: white;'></span></div>".html_safe, :authorizations
            .row
              .col-md-12
                %button.pull-right.btn.btn-primary.form-control{:type => :submit, :name => "commit"}
                  %span.glyphicon.glyphicon-check
                  Save
        .panel-footer
          %p.text-muted Write permission automatically grants read permission.
          %p.text-muted If a user is not listed, they do not have permission to your table.
  .row
    .col-md-12
      .panel.panel-danger
        .panel-heading.text-center
          %h1
            %strong
              %span.glyphicon.glyphicon-warning-sign
              DANGER ZONE
              %span.glyphicon.glyphicon-warning-sign
        .panel-body
          = form_for @equipment_group do |f|
            .row.push-bottom
              .col-md-6
                Make Table Public?
              .col-md-4
                = f.select :public_access, options_for_select({ "True" => true, "False" => false }, f.object.public_access), {}, { :class => 'form-control' }
              .col-md-2
                %button.pull-right.btn.btn-primary.form-control{:type => :submit, :name => "commit"}
                  %span.glyphicon.glyphicon-check
                  Save
            .row.push-bottom
              .col-md-6
                Change Ownership?
              .col-md-4
                = f.collection_select :user_id, User.order('username ASC').all, :id, :username, {}, :class => 'form-control'
              .col-md-2
                %button.pull-right.btn.btn-primary.form-control{:type => :submit, :name => "commit"}
                  %span.glyphicon.glyphicon-check
                  Save
            .row
              .col-md-12
                %a.form-control.btn.btn-danger{ :href => equipment_group_path(@equipment_group), :style => 'color: white;', :data => { :method => :delete, :confirm => 'Are you sure?' } }
                  %strong
                    %span.glyphicon.glyphicon-fire
                    DESTROY TABLE (this cannot be undone)
                    %span.glyphicon.glyphicon-fire
        .panel-footer
          %p.text-muted Public access only applies to read permissions. There is no public write permission.
          %p.text-muted Don't lock yourself out! If you need to maintain read or write access to this table, give yourself permissions before you change owner.

app/views/equipment_groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @equipment_group.name
%p
  %b Name position:
  = @equipment_group.name_position

= link_to 'Edit', edit_equipment_group_path(@equipment_group)
\|
= link_to 'Back', equipment_groups_path

app/views/equipment_groups/table.html.haml
.container
  .row
    .col-md-6
      %h1
        %strong
          = @equipment_group.name
    .col-md-1
      %a.btn.btn-primary.form-control{:href => tv_mode_path(@equipment_group), :style => 'color: white; margin-top: 25px;', :rel => "tooltip", :title => "TV Mode", :data => { :toggle => "tooltip", :placement => "top", :container => "body" } }
        %span.glyphicon.glyphicon-fullscreen
    - if user_signed_in?
      - if current_user.is_owner(@equipment_group)
        .col-md-3
          %a.btn.btn-success.form-control{:href => new_row_simple_path(@equipment_group), :style => 'color: white; margin-top: 25px;'}
            %span.glyphicon.glyphicon-list-alt
            Take new measurement
        .col-md-2
          %a.btn.btn-warning.form-control{:href => equipment_group_settings_path(@equipment_group), :style => 'color: white; margin-top: 25px;'}
            %span.glyphicon.glyphicon-cog
            Settings
      - elsif current_user.can_write(@equipment_group)
        .col-md-5
          %a.btn.btn-success.form-control{:href => new_row_simple_path(@equipment_group), :style => 'color: white; margin-top: 25px;'}
            %span.glyphicon.glyphicon-list-alt
            Take new measurement
  .row
    .col-md-12
      / This is so unthinkably nasty...
      :erb
        <% if POLLING_ENABLED %>
          <script>
            $(function () {
              $('#table').html("<iframe id='iframe' scrolling='no' frameborder='0' style='width: 100%; margin: 0px; padding: 0px; overflow: hidden;' src='<%= just_the_table_path(@equipment_group) %>'></iframe>");
              $(document).ready(function(){
                  $('iframe').each(function(){
                      var context = $(this);
                      context.load(function(event){ // attach the onload event to the iframe
                          var body = $(this.contentWindow.document).find('body');
                          if (body.length > 0 && $(body).find('*').length > 0) { // check if iframe has contents
                              context.height($(body.get(0)).height() + 20);
                          } else {
                              context.hide(); // hide iframes with no contents
                          }
                      });
                  });
              });
            });
            window.setInterval(function(){
              $('#table').html("<iframe id='iframe' scrolling='no' frameborder='0' style='width: 100%; margin: 0px; padding: 0px; overflow: hidden;' src='<%= just_the_table_path(@equipment_group) %>'></iframe>");
              $(document).ready(function(){
                  $('iframe').each(function(){
                      var context = $(this);
                      context.load(function(event){ // attach the onload event to the iframe
                          var body = $(this.contentWindow.document).find('body');
                          if (body.length > 0 && $(body).find('*').length > 0) { // check if iframe has contents
                              context.height($(body.get(0)).height() + 20);
                          } else {
                              context.hide(); // hide iframes with no contents
                          }
                      });
                  });
              });
            }, 60000);
          </script>
          <div id='table'></div>
        <% else %>
          <%= render 'just_the_table' %>
        <% end %>
  - if user_signed_in?
    - if current_user.is_owner(@equipment_group)
      .row
        = nested_form_for @equipment_group do |f|
          .col-md-12
            #accordion1.panel-group
              .panel.panel-warning
                .panel-heading
                  %h3.panel-title.text-center
                    %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseEquipment"}
                      %span.glyphicon.glyphicon-plus
                      Modify Equipment
                      %span.glyphicon.glyphicon-pencil
                #collapseEquipment.panel-collapse.collapse
                  .panel-body
                    = f.fields_for :equipment do |ef|
                      .row
                        .col-md-6
                          .form-group
                            %label Name
                            = ef.text_field :name, :class => "form-control"
                        .col-md-1
                          .form-group
                            %label Position
                            = ef.number_field :name_position, :class => "form-control"
                          = ef.hidden_field :equipment_group_id, :value => @equipment_group.id
                        - if ef.object.id
                          .col-md-3
                            %a.btn.btn-warning{:href => edit_equipment_path(ef.object), :style => 'color: white; margin-top: 25px;'}
                              %span.glyphicon.glyphicon-pencil
                              Modify Measurements
                        .col-md-2
                          .form-group
                            = ef.link_to_remove "<div class='btn btn-md btn-danger' style='margin-top: 25px;'><span class='glyphicon glyphicon-minus' style='color: white;'></span></div>".html_safe
                    .row
                      .col-md-12
                        = f.link_to_add "<div class='btn btn-md btn-success'><span class='glyphicon glyphicon-plus' style='color: white;'></span></div>".html_safe, :equipment

                        %br
                        %br
                    .row
                      .col-md-12
                        %button.pull-right.btn.btn-primary.form-control{:type => :submit, :name => "commit"}
                          %span.glyphicon.glyphicon-check
                          Save
                        %br
                        %br
                        %br
                    .row
                      .col-md-12
                        .text-muted
                          %strong Note:
                          Equipment without measurements will not be shown. Add a new measurement by clicking "Modify Measurements".

app/views/equipment_groups/tv_mode.html.haml
.container
  .row
    .col-md-12
      / This is so unthinkably nasty...
      :erb
        <% if POLLING_ENABLED %>
          <script>
            $(function () {
              $('#table').html("<iframe id='iframe' scrolling='no' frameborder='0' style='width: 100%; margin: 0px; padding: 0px; overflow: hidden;' src='<%= just_the_table_path(@equipment_group) %>'></iframe>");
              $(document).ready(function(){
                  $('iframe').each(function(){
                      var context = $(this);
                      context.load(function(event){ // attach the onload event to the iframe  
                          var body = $(this.contentWindow.document).find('body');
                          if (body.length > 0 && $(body).find('*').length > 0) { // check if iframe has contents
                              context.height($(body.get(0)).height() + 20);
                          } else {
                              context.hide(); // hide iframes with no contents
                          }
                      });
                  });
              });
            });
            window.setInterval(function(){
              $('#table').html("<iframe id='iframe' scrolling='no' frameborder='0' style='width: 100%; margin: 0px; padding: 0px; overflow: hidden;' src='<%= just_the_table_path(@equipment_group) %>'></iframe>");
              $(document).ready(function(){
                  $('iframe').each(function(){
                      var context = $(this);
                      context.load(function(event){ // attach the onload event to the iframe  
                          var body = $(this.contentWindow.document).find('body');
                          if (body.length > 0 && $(body).find('*').length > 0) { // check if iframe has contents
                              context.height($(body.get(0)).height() + 20);
                          } else {
                              context.hide(); // hide iframes with no contents
                          }
                      });
                  });
              });
            }, 60000);
          </script>
          <div id='table'></div>
        <% else %>
          <%= render 'just_the_table' %>
        <% end %>