config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :equipment_groups, only: [:new, :index, :create, :update, :destroy]
  get 'equipment_groups/:id/table' => 'equipment_groups#table', as: :equipment_group_table
  get 'equipment_groups/:id/just_the_table' => 'equipment_groups#just_the_table', as: :just_the_table
  get 'equipment_groups/:id/tv_mode' => 'equipment_groups#tv_mode', as: :tv_mode
  get 'equipment_groups/:id/settings' => 'equipment_groups#settings', as: :equipment_group_settings
  resources :equipment, only: [:edit, :update]
  resources :log_entries, only: [:create]
  get 'log_entries/new_row/:id' => 'log_entries#new_row', as: :new_row
  get 'log_entries/new_row_simple/:id' => 'log_entries#new_row_simple', as: :new_row_simple

end

app/models/log_entry.rb
class LogEntry < ActiveRecord::Base
  has_paper_trail
  has_many :values
  accepts_nested_attributes_for :values
end

app/controllers/log_entries_controller.rb
class LogEntriesController < ApplicationController
  before_action :set_equipment_group, only: [:new_row, :new_row_simple]
  before_filter :authenticate

  # POST /log_entries
  # POST /log_entries.json
  def create
    @log_entry = LogEntry.new(log_entry_params)

    respond_to do |format|
      if @log_entry.save
        format.html { redirect_to equipment_group_table_path(EquipmentGroup.find(Equipment.find(Measurement.find(@_params[:log_entry][:values_attributes]["0"][:measurement_id]).equipment_id).equipment_group_id)), notice: 'Log entry was successfully created.' }
        format.json { render :show, status: :created, location: @log_entry }
      else
        format.html {
          if @log_entry.errors.any?
            flash[:alert] = @log_entry.errors.full_messages.join(". ")
          end
          redirect_to new_row_path(EquipmentGroup.find(Equipment.find(Measurement.find(@_params[:log_entry][:values_attributes]["0"][:measurement_id]).equipment_id).equipment_group_id))
        }
        format.json { render json: @log_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_row
    if current_user.is_owner(@equipment_group) or current_user.can_write(@equipment_group)
    else
      redirect_to equipment_group_table_path(@equipment_group), :alert => "You can't write here (no permission)."
    end
    @log_entry = LogEntry.new
  end

  def new_row_simple
    if current_user.is_owner(@equipment_group) or current_user.can_write(@equipment_group)
    else
      redirect_to equipment_group_table_path(@equipment_group), :alert => "You can't write here (no permission)."
    end
    @log_entry = LogEntry.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log_entry
      @log_entry = LogEntry.find(params[:id])
    end

    def set_equipment_group
      @equipment_group = EquipmentGroup.find(params[:id])
      @equipment = @equipment_group.equipment
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def log_entry_params
      params.require(:log_entry).permit(:capture_date, values_attributes: [:id, :value, :tolerance, :upper_bound, :lower_bound, :true_label, :false_label, :not_applicable, :measurement_id, :log_entry_id, :_destroy])
    end
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/views/log_entries/_form.html.haml
%h1 Just a form

app/views/log_entries/edit.html.haml
%h1 Editing log_entry

= render 'form'

= link_to 'Show', @log_entry
\|
= link_to 'Back', log_entries_path

app/views/log_entries/index.html.haml
%h1 Listing log_entries

%table
  %tr
    %th Capture date
    %th
    %th
    %th

  - @log_entries.each do |log_entry|
    %tr
      %td= log_entry.capture_date
      %td= link_to 'Show', log_entry
      %td= link_to 'Edit', edit_log_entry_path(log_entry)
      %td= link_to 'Destroy', log_entry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Log entry', new_log_entry_path

app/views/log_entries/new.html.haml
= render 'form'

= link_to 'Back', log_entries_path

app/views/log_entries/new_row.haml
- @value = @log_entry.values.build
= nested_form_for @log_entry do |f|
  .container
    - if @log_entry.errors.any?
      .row
        .col-md-12
          #error_explanation
            %h2= "#{pluralize(@log_entry.errors.count, "error")} prohibited this log_entry from being saved:"
            %ul
              - @log_entry.errors.full_messages.each do |msg|
                %li= msg
    .row
      .col-md-12
        %h1
          %strong
            = @equipment_group.name
    .row
      .col-md-12
        %table.table.table-condensed.table-striped
          %thead
            %tr
              %th Equipment
              %th Measurement
              %th Unit
              %th Lower Bound
              %th Upper Bound
              %th True Label
              %th False Label
              %th Tolerance (Decimal < 1)
              %th True/False?
              %th N/A
              %th
                Value On:
                %br
                .form-group
                  #datetimepicker1.input-group.date
                    = f.text_field :capture_date, value: Time.now, :class => 'form-control', :style => 'font-size: 70%;', "data-date-format" => "YYYY-MM-DD HH:mm:ss ZZ"
                    %span.input-group-addon
                      %span.glyphicon.glyphicon-calendar
                :javascript
                  $(function () {
                      $('#datetimepicker1').datetimepicker({

                        });
                  });
              %th
                %span.glyphicon.glyphicon-heart-empty
          - @equipment.order(:name_position).each do |e|
            - e.measurements.order(:name_position).each do |m|
              %tr
              - if m === e.measurements.order(:name_position).first
                %td= e.name
              - else
                %td
              %td= m.name
              %td= m.unit
              - if m.values.empty?
                = f.fields_for :values do |value_form|
                  - if m.is_bool
                    %td= value_form.select :lower_bound, options_for_select({ "True" => 1.0, "False" => 0.0 }), {}, { :class => 'short form-control lower_bound' }
                  - else
                    %td= value_form.text_field :lower_bound, :class => 'short form-control lower_bound'
                  - if m.is_bool
                    %td= value_form.select :upper_bound, options_for_select({ "True" => 1.0, "False" => 0.0 }), {}, { :class => 'short form-control upper_bound' }
                  - else
                    %td= value_form.text_field :upper_bound, :class => 'short form-control upper_bound'
                  - if m.is_bool
                    %td= value_form.text_field :true_label, value: "True", :class => 'short form-control true_label'
                  - else
                    %td.true_label
                  - if m.is_bool
                    %td= value_form.text_field :false_label, value: "False", :class => 'short form-control false_label'
                  - else
                    %td.false_label
                  - if m.is_bool
                    %td= value_form.text_field :tolerance, value: 0.0, :class => 'short form-control tolerance'
                  - else
                    %td= value_form.text_field :tolerance, :class => 'short form-control tolerance'
                  %td.text-center
                    %strong.is_bool= m.is_bool ? 'Yes' : 'No'
                  %td= value_form.check_box :not_applicable, :class => 'short form-control'
                  - if m.is_bool
                    %td= value_form.select :value, options_for_select({ "True" => 1.0, "False" => 0.0 }), {}, { :class => 'short form-control value' }
                  - else
                    %td= value_form.text_field :value, :class => 'short form-control value'
                  = value_form.hidden_field :measurement_id, value: m.id
                  = value_form.hidden_field :log_entry_id, value: @log_entry.id
              - else
                = f.fields_for :values do |value_form|
                  - if m.is_bool
                    %td= value_form.select :lower_bound, options_for_select({ m.values.last.true_label => 1.0, m.values.last.false_label => 0.0 }, m.values.last.lower_bound), {}, { :class => 'short form-control lower_bound' }
                  - else
                    %td= value_form.text_field :lower_bound, value: m.values.last.lower_bound, :class => 'short form-control lower_bound'
                  - if m.is_bool
                    %td= value_form.select :upper_bound, options_for_select({ m.values.last.true_label => 1.0, m.values.last.false_label => 0.0 }, m.values.last.upper_bound), {}, { :class => 'short form-control upper_bound' }
                  - else
                    %td= value_form.text_field :upper_bound, value: m.values.last.upper_bound, :class => 'short form-control upper_bound'
                  %td= value_form.text_field :true_label, value: m.values.last.true_label, :class => 'short form-control true_label'
                  %td= value_form.text_field :false_label, value: m.values.last.false_label, :class => 'short form-control false_label'
                  - if m.is_bool
                    %td= value_form.text_field :tolerance, value: 0.0, :class => 'short form-control tolerance'
                  - else
                    %td= value_form.text_field :tolerance, value: m.values.last.tolerance, :class => 'short form-control tolerance'
                  %td.text-center
                    %strong.is_bool= m.is_bool ? 'Yes' : 'No'
                  %td= value_form.check_box :not_applicable, value: m.values.last.not_applicable, :class => 'short form-control not_applicable'
                  - if m.is_bool
                    %td= value_form.select :value, options_for_select({ m.values.last.true_label => 1.0, m.values.last.false_label => 0.0 }, m.values.last.value), {}, { :class => 'longer form-control value' }
                  - else
                    %td= value_form.text_field :value, value: m.values.last.value, :class => 'short form-control value'
                  %td
                    %span.verify-icon.glyphicon
                  = value_form.hidden_field :measurement_id, value: m.id
                  = value_form.hidden_field :log_entry_id, value: @log_entry.id
    .row
      .col-md-12
        / = f.submit "Save"
        %button.pull-right.btn.btn-primary.form-control{:type => :submit, :name => "commit"}
          %span.glyphicon.glyphicon-check
          Save

app/views/log_entries/new_row_simple.haml
- @value = @log_entry.values.build
= nested_form_for @log_entry do |f|
  .container
    - if @log_entry.errors.any?
      .row
        .col-md-12
          #error_explanation
            %h2= "#{pluralize(@log_entry.errors.count, "error")} prohibited this log_entry from being saved:"
            %ul
              - @log_entry.errors.full_messages.each do |msg|
                %li= msg
    .row
      .col-md-6
        %h1
          %strong
            = @equipment_group.name
      .col-md-6
        %a.btn.btn-success.form-control{:href => new_row_path(@equipment_group), :style => 'color: white; margin-top: 25px;'}
          %span.glyphicon.glyphicon-list-alt
          Advanced measurement
    .row
      .col-md-12
        %table.table.table-condensed.table-striped.simple
          %thead
            %tr
              %th Equipment
              %th Measurement
              %th Unit
              %th Lower Bound
              %th Upper Bound
              %th True Label
              %th False Label
              %th Tolerance (Decimal < 1)
              %th True/False?
              %th N/A
              %th
                Value On:
                %br
                .form-group
                  #datetimepicker1.input-group.date
                    = f.text_field :capture_date, value: Time.now, :class => 'form-control', :style => 'font-size: 70%;', "data-date-format" => "YYYY-MM-DD HH:mm:ss ZZ"
                    %span.input-group-addon
                      %span.glyphicon.glyphicon-calendar
                :javascript
                  $(function () {
                      $('#datetimepicker1').datetimepicker({

                        });
                  });
              %th
                %span.glyphicon.glyphicon-heart-empty
          - @equipment.order(:name_position).each do |e|
            - e.measurements.order(:name_position).each do |m|
              %tr
              - if m === e.measurements.order(:name_position).first
                %td= e.name
              - else
                %td
              %td= m.name
              %td= m.unit
              - if m.values.empty?
                %td{:colspan => '9'}
                  Use the
                  %a{:href => '#'} advanced form
                  for your new blank measurements.
                  (So you can set bounds and tolerance)
              - else
                = f.fields_for :values do |value_form|
                  - if m.is_bool
                    %td.lower_bound= m.values.last.lower_bound
                    = value_form.hidden_field :lower_bound, value: m.values.last.lower_bound
                  - else
                    %td.lower_bound= m.values.last.lower_bound
                    = value_form.hidden_field :lower_bound, value: m.values.last.lower_bound
                  - if m.is_bool
                    %td.upper_bound= m.values.last.upper_bound
                    = value_form.hidden_field :upper_bound, value: m.values.last.upper_bound
                  - else
                    %td.upper_bound= m.values.last.upper_bound
                    = value_form.hidden_field :upper_bound, value: m.values.last.upper_bound
                  %td.true_label= m.values.last.true_label
                  = value_form.hidden_field :true_label, value: m.values.last.true_label
                  %td.true_label= m.values.last.false_label
                  = value_form.hidden_field :false_label, value: m.values.last.false_label
                  - if m.is_bool
                    %td.tolerance= 0.0
                    = value_form.hidden_field :tolerance, value: 0.0
                  - else
                    %td.tolerance= m.values.last.tolerance
                    = value_form.hidden_field :tolerance, value: m.values.last.tolerance
                  %td.text-center
                    %strong.is_bool= m.is_bool ? 'Yes' : 'No'
                  %td.not_applicable= value_form.check_box :not_applicable, value: m.values.last.not_applicable, :class => 'short form-control not_applicable'
                  - if m.is_bool
                    %td.value= value_form.select :value, options_for_select({ m.values.last.true_label => 1.0, m.values.last.false_label => 0.0 }, m.values.last.value), {}, { :class => 'longer form-control value' }
                  - else
                    %td.value= value_form.text_field :value, value: m.values.last.value, :class => 'short form-control value'
                  %td
                    %span.verify-icon.glyphicon
                  = value_form.hidden_field :measurement_id, value: m.id
                  = value_form.hidden_field :log_entry_id, value: @log_entry.id
    .row
      .col-md-12
        / = f.submit "Save"
        %button.pull-right.btn.btn-primary.form-control{:type => :submit, :name => "commit"}
          %span.glyphicon.glyphicon-check
          Save

app/views/log_entries/show.html.haml
%p#notice= notice

%p
  %b Capture date:
  = @log_entry.capture_date

= link_to 'Edit', edit_log_entry_path(@log_entry)
\|
= link_to 'Back', log_entries_path